# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0002_auto_20161214_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='_friend_friends_+', to='friends.Friend')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginapp.User')),
            ],
        ),
    ]
